# Spring properties
spring:
  application:
    name: configuration-service
    #Avoid name clashing
  main:
    allow-bean-definition-overriding: true

# HTTP Server
server:
  port:  ${SERVICE_PORT:@service.port@}

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:
  instance:
    hostname: ${CONTAINER_IP:@container.ip@}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${RS_PORT_1111_TCP_ADDR:@rs.ip@}:${RS_PORT_1111_TCP_PORT:@rs.port@}/eureka/

persistenceservice:
  url: http://PERSISTENCE-SERVICE
timeconsumingservice:
  url: http://TIMECONSUMING-SERVICE

# Disabling security for Actuator' REST services
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
#  endpoint:
#    health:
#      enabled: true
#    info:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: beans, loggers, actuator

