spring:
  application:
    name: persistence-service

  # Database configuration
  # Spring Boot automatically creates a JPA EntityManagerFactory using Hibernate
  # but we need to override some defaults:
  #
  #   1. Stop Hibernate automatically creating a schema, we are doing it in
  #      schema.sql. Instead check the tables match their JPA mapped classes
  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: HSQL
    show-sql: true

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

# HTTP Server
server:
  port: ${SERVICE_PORT:@service.port@}

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:
  instance:
    hostname: ${CONTAINER_IP:@container.ip@}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${RS_PORT_1111_TCP_ADDR:@rs.ip@}:${RS_PORT_1111_TCP_PORT:@rs.port@}/eureka/

#Test db
testDatasource:
  jdbc-url: jdbc:hsqldb:file:testdb
  username: SA
  password:
  driver-class-name: org.hsqldb.jdbcDriver

# Disabling security for Actuator' REST services
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
